### ISSUE TITLE
[Question] Is there a way I can apply the browser to other docs?

### ISSUE THREAD

**Issue by liquidsaul** [hcabel/UnrealVsCodeHelper#1]
Title really says this all.

Would like to use it for the Kubernetes Documentation

**Comment by hcabel** [comment]
Hello liquidsaul,
it's actually work in progress, you will soon be able specified the list of the website that the query will look into.

Are you using Kubernetes with unreal ?
Because if you don't use unreal I was thinking about splitting the browser feature into her own extension since other people have the same issue has you. (UVCH will still have this feature but has a dependencie to the other extension and with a custom config for UE)

**Comment by hcabel** [comment]
I just release a new version where your able to specified the `AllowedWebsite` of you search.
I close this issue but if it's not working your very welcome to reply to this one and I'll reopen it :)

**Comment by liquidsaul** [comment]
@hcabel I don't use Unreal with Kubernetes and the splitting out would be pretty neat :)
